Fix openning message with expired pass phrase
FlowCrypt/flowcrypt-ios pull request #431
Opened 2021-08-05 15:55 UTC by Kharchevskyi

This PR fixes bug when pass phrase expired

close #426

For testing purposes timeout can be changed in `InMemoryPassPhraseStorage`
----------------------------------

**Tests** :
- Difficult to test. Time consuming
--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

2021-08-05 19:24 UTC, tomholub reviewed
Does this still allow me to view list of keys in Settings -> Keys section when the pass phrase expired?

2021-08-06 08:36 UTC, Kharchevskyi commented
> Does this still allow me to view list of keys in Settings -> Keys section when the pass phrase expired?

hm...good catch, I assume - no. Will fix

2021-08-06 09:50 UTC, tomholub commented
The design of this method needs to change. It's good that it collects pass phrases, but it should not be required. It's ok to return keys missing pass phrases if they are missing. Let the downstream code deal with that.

2021-08-06 10:46 UTC, Kharchevskyi reviewed
LGTM

2021-08-06 12:57 UTC, tomholub requested changes

2021-08-06 12:57 UTC, tomholub commented on FlowCrypt/Functionality/Services/Key Services/KeyService.swift
>      func retrieveKeyDetails() -> Result<[KeyDetails], KeyServiceError> {
The difference between `retrieveKeyDetails` and `getPrivateKeys` is not obvious from the name. Let's rename it:
 - `retrieveKeyDetails` -> `getPrvKeyDetails`
 - `getPrivateKeys` -> `getPrvKeyInfo`

Still not so obvious, but at least it highlights the different formats.

Then, please add a comment to highlight what is each method for, why do we have two similar methods.

2021-08-08 13:28 UTC, tomholub approved these changes

2021-08-08 13:43 UTC, merged